const ACCOUNT = {
  FETCH: "ACCOUNT_FETCH",
  FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
  FETCH_LOGOUT_SUCCESS: "ACCOUNT_FETCH_LOGOUT_SUCCESS",
  FETCH_AUTHENTICATED_SUCCESS: "ACCOUNT_FETCH_AUTHENTICATED_SUCCESS",
  FETCH_GOOGLE_USER_SUCCESS: "ACCOUNT_FETCH_GOOGLE_USER_SUCCESS",
};

const ACCOUNT_INFO = {
  FETCH: "ACCOUNT_INFO_FETCH",
  FETCH_ERROR: "ACCOUNT_INFO_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_INFO_FETCH_SUCCESS",
};

const PROPOSAL = {
  FETCH: "PROPOSAL_FETCH",
  FETCH_ERROR: "PROPOSAL_FETCH_ERROR",
  FETCH_SUCCESS: "PROPOSAL_FETCH_SUCCESS",
  EDIT: "PROPOSAL_EDIT",
};

const ABOUTUS = {
  FETCH: "ABOUTUS_FETCH",
  FETCH_ERROR: "ABOUTUS_FETCH_ERROR",
  FETCH_SUCCESS: "ABOUTUS_FETCH_SUCCESS",
  SAVE_TEXT: "ABOUTUS_SAVE_TEXT",
  UPDATE_TOUCHED: "ABOUTUS_UPDATE_TOUCHED",
  SHOW_DEFAULT: "ABOUTUS_SHOW_DEFAULT",
  DELETE_TEXT: "ABOUTUS_DELETE_TEXT",
  CREATE_TEXT: "ABOUTUS_CREATE_TEXT",
  CLEAR_STATE: "ABOUTUS_CLEAR_STATE",
};
const APPROACH = {
  FETCH: "APPROACH_FETCH",
  FETCH_ERROR: "APPROACH_FETCH_ERROR",
  FETCH_SUCCESS: "APPROACH_FETCH_SUCCESS",
  SAVE_TEXT: "APPROACH_SAVE_TEXT",
  UPDATE_TOUCHED: "APPROACH_UPDATE_TOUCHED",
  SHOW_DEFAULT: "APPROACH_SHOW_DEFAULT",
  CREATE_TEXT: "APPROACH_CREATE_TEXT",
  DELETE_TEXT: "APPROACH_DELETE_TEXT",
  CLEAR_STATE: "APPROACH_CLEAR_STATE",
};
const OFFER = {
  FETCH: "OFFER_FETCH",
  FETCH_ERROR: "OFFER_FETCH_ERROR",
  FETCH_SUCCESS: "OFFER_FETCH_SUCCESS",
  SAVE_CARD: "OFFER_SAVE_CARD",
  UPDATE_CARD: "OFFER_UPDATE_CARD",
  SHOW_DEFAULT: "OFFER_SHOW_DEFAULT",
  CREATE_CARD: "OFFER_CREATE_CARD",
  DELETE_CARD: "OFFER_DELETE_CARD",
  CLEAR_STATE: "OFFER_CLEAR_STATE",
};
const OPTION_CARD = {
  FETCH: "OPTION_CARD_FETCH",
  FETCH_ERROR: "OPTION_CARD_FETCH_ERROR",
  FETCH_SUCCESS: "OPTION_CARD_FETCH_SUCCESS",
  SAVE_CARD: "OPTION_CARD_SAVE_CARD",
  UPDATE_CARD: "OPTION_CARD_UPDATE_CARD",
  SHOW_DEFAULT: "OPTION_CARD_SHOW_DEFAULT",
  CREATE_OPTION_CARD: "OPTION_CARD_CREATE_OPTION_CARD",
  DELETE_TEXT: "OPTION_CARD_DELETE_TEXT",
  CLEAR_STATE: "OPTION_CARD_CLEAR_STATE",
};

export {
  ACCOUNT,
  ACCOUNT_INFO,
  PROPOSAL,
  ABOUTUS,
  APPROACH,
  OFFER,
  OPTION_CARD,
};
